/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DownloadCard: (typeof import('./src/components/downloadCard/DownloadCard.vue'))['default']
    NEXUSe2eImage: (typeof import('./src/components/nexus2eImage/NEXUSe2eImage.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    TheNewNavigationDrawer: (typeof import('./src/components/theNewNavigationDrawer/TheNewNavigationDrawer.vue'))['default']
    TheNewToolbar: (typeof import('./src/components/theNewToolbar/TheNewToolbar.vue'))['default']
    TheOldNavigationDrawer: (typeof import('./src/components/theOldNavigationDrawer/TheOldNavigationDrawer.vue'))['default']
    TheOldToolbar: (typeof import('./src/components/theOldToolbar/TheOldToolbar.vue'))['default']
  }
}
