/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DownloadCard: typeof import('./src/components/downloadCard/DownloadCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NgImage: typeof import('./src/components/theImage/NgImage.vue')['default']
    NgImg: typeof import('./src/components/ngImg/NgImg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheImage: typeof import('./src/components/theImage/TheImage.vue')['default']
    TheNewNavigationDrawer: typeof import('./src/components/theNewNavigationDrawer/TheNewNavigationDrawer.vue')['default']
    TheNewToolbar: typeof import('./src/components/theNewToolbar/TheNewToolbar.vue')['default']
    TheOldNavigationDrawer: typeof import('./src/components/theOldNavigationDrawer/TheOldNavigationDrawer.vue')['default']
    TheOldToolbar: typeof import('./src/components/theOldToolbar/TheOldToolbar.vue')['default']
  }
}
